[project]
name = "graphqec"
version = "0.1.0"
description = "A collection of QEC implementations."
authors = [{ name = "Adel Sohbi", email = "adel.sohbi@gmail.com" }]
readme = "README.md"
dependencies = [
    "numpy>=1.26,<2",
    "scipy>=1.14",
    "stim>=1.14.0",
    "pymatching>=2.2.1",
    "jupyter>=1.1.1",
    "ipykernel>=6.29.5",
    "networkx>=3.4.2"
]

[project.optional-dependencies]
docs = [
]
dev = [
  "pytest>=8.0",
  "pytest-cov>=3.0.0",
  "black>=24.10.0",
  "flake8>=7.1.1",
  "pre-commit>=4.0.1"
]

[tool.setuptools]
packages = ["graphqec"]
include-package-data = true

[tool.black]
line-length = 88
